sudo: required
arch:
  - amd64
  - arm64
script: make travis
install:
  # AWS CLI is required for pushing the edge binaries to S3.
  - pip install --user awscli
env:
  global:
  - secure: "STFHbK4N70sU+mekByuMx6uQTcAhD7sy+PEJUILlTnL2O56OlCuyjFt8nQ28LCEhLd1HJ+SQff7Uuv4jBkYLfhrR3ptQ5l5AdRpPBQ9PcH839DloAdOB/V7Rkfe15QlUaphvNe6lcsMt+i0TnfEJ0adh784h5B8jA9KiXE7LDfbxKBj8KewfRRlHnyH/H0Qy8Wk4afVNqTUbFucbSm82IneykzHEhIMOsY1/CqbMndUFmrs/TmRY0+K2YVw7sAMobrXWgCuYJo3e5xDGqi3zm2i8/AQHpbx0dYjTJWTnv7inujvCABLCsI1hKqMarOQr4COHk6wBOXMClLOSl7JmmFm5vmQIZyWBRJHZBbbloQGWMDjw/BniV3K9W33tfq3s90cI0MqtjSSwdY/l6tBMMxtIyUTDtOqF576OFghYdvA39MShzI1KC0qh2a9x6Bk15ATRMdTRCXPM6ZIZaIlmuP4Z1ETuQ3MUIpiQpJxKfeZ3UHwxMoSP9R8LzR2qFT+AauW8E+0nVf+mOYEDgenuAvX5b+rEAN1E8ef9HTHzhW8tjSZxLU1P5jaWAFZUw3/T0E0/XdieJOyTzwR/7ZHivceODz/x7GWg9HiwFPxt4PvYTw5QjPqkruq7YMP0B7aX7gF+30nEG8ljJT6egGJ1scLDv7pc/J28O8GAwo2YgeE="
  - secure: "PHiSwVZvWhSalyPgZ2vXpl8MKOzoyZdDr2Ib8n7Dx8iOEhm3QFbnxhLHfFI01Uy0rSbEFY8ZKarmOcmK1tyOKjXHi7byx8/HArXKiOB4kNEGBdtXZirJtc5OKkzdG8Q66E8m5NKU8Psi9Id3tHDlWF4akqzWREyNHyDo5ZH1t20q79PisTZ6YJKU9P4QZP/iO3NtudUetZHege77NU4e1Ivj/Xsj7nlY8sXdZV7XkNfvr2XXW2GKZ7HBBAuxohPdt8dYL1iMyf7MddDJAuPrScJZj+hqthz2CIR5l6Ep0P2k6Fz02sUloGr4EcOKQISC4QQf27Ggp6DtFIXCKBYKQ3tMl+kV+76Ds6o0Fi/npCGrCNXpUzT1QYNFDMHmyMPDsbBppJV1X4FuljAEOg01+ASIn9WDeTovkafYNdgdtBP9e7dX7BeopA+lwZQmtGwerCdg0MNaQwk8lS8Q8TzKqKeAfaXKPxwoDpKAFPjS4N0MNPQ4EXSWPoGaXAChK3MD6EdLUGdW23n9swJ8RMfH3snouMnuzLUYdUP7NdjG4+uesKESyfRpTU1guBRRJ8JIaiZXdsum1BK4W3p5WjWS/dFD83nkhNzJJ9cTcOxR3b2RP8ymGuOyLTtPiEfR4dC18oBwsJpJtohspWdcl2RslEet0HRERDDJb3F3bsaAVcA="
services:
- docker
deploy:


  # This deployment is mutually exclusive with the other deployments. This
  # deployment builds and publishes the docker image whenever changes are
  # committed to master. The edge tag is updated to track this version.
  # The latest tag is not updated.
  - provider: script
    skip_cleanup: true  # do not delete artifacts because linux executable is needed
    script: make deploy-travis
    on:
      repo: open-policy-agent/opa
      branch: master
      tags: false

  # This deployment is mutually exclusive with the other deployments. This
  # deployment builds and publishes the docker image whenever a new tag is
  # created on the master branch. The latest tag is updated to point to the
  # image produced by this deployment. The edge tag is not updated.
  - provider: script
    skip_cleanup: true  # do not delete artifacts because linux executable is needed
    script: make release-travis
    on:
      repo: open-policy-agent/opa
      branch: master
      tags: true

  # This deployment is mutually exclusive with the other deployments. This
  # deployment builds and publishes the docker image whenever a new tag is
  # created on a release branch.
  - provider: script
    skip_cleanup: true  # do not delete artifacts because linux executable is needed
    script: make release-bugfix-travis
    on:
      repo: open-policy-agent/opa
      condition: $TRAVIS_BRANCH =~ ^release-.*$
      tags: true
